//微信表情代码
module.exports = {
  wx : '/::)', //微笑
  pz : '/::~', //撇嘴
  se : '/::B', //色
  fd : '/::|', //发呆
  dy : '/:8-)', //得意
  ll : '/::<', //流泪
  hx : '/::$', //害羞
  bz : '/::X', //闭嘴
  shui : '/::Z', //睡
  dk : '/::\'(', //大哭
  gg : '/::-|', //尴尬
  fn : '/::@', //发怒
  tp : '/::P', //调皮
  cy : '/::D', //呲牙
  jy : '/::O', //惊讶
  ng : '/::(', //难过
  kuk : '/::+', //酷
  lengh : '/:--b', //冷汗
  zk : '/::Q', //抓狂
  tuu : '/::T', //吐
  tx : '/:,@P', //偷笑
  ka : '/:,@-D', //可爱
  baiy : '/::d', //白眼
  am : '/:,@o', //傲慢
  jie : '/::g', //饥饿
  kun : '/:|-)', //困
  jk : '/::!', //惊恐
  lh : '/::L', //流汗
  hanx : '/::>', //憨笑
  db : '/::,@', //大兵
  fendou : '/:,@f', //奋斗
  zhm : '/::-S', //咒骂
  yiw : '/:?', //疑问
  xu : '/:,@x', //嘘...
  yun : '/:,@@', //晕
  zhem : '/::8', //折磨
  shuai : '/:,@!', //衰
  kl : '/:!!!', //骷髅
  qiao : '/:xx', //敲打
  zj : '/:bye', //再见
  ch : '/:wipe', //擦汗
  kb : '/:dig', //抠鼻
  gz : '/:handclap', //鼓掌
  qd : '/:&-(', //糗大了
  huaix : '/:B-)', //坏笑
  zhh : '/:<@', //左哼哼
  yhh : '/:@>', //右哼哼
  hq : '/::-O', //哈欠
  bs : '/:>-|', //鄙视
  wq : '/:P-(', //委屈
  kk : '/::\'|', //快哭了
  yx : '/:X-)', //阴险
  qq : '/::*', //亲亲
  xia : '/:@x', //吓
  kel : '/:8*', //可怜
  cd : '/:pd', //菜刀
  xig : '/:<W>', //西瓜
  pj : '/:beer', //啤酒
  lq : '/:basketb', //篮球
  pp : '/:oo', //乒乓
  kf : '/:coffee', //咖啡
  fan : '/:eat', //饭
  zt : '/:pig', //猪头
  mg : '/:rose', //玫瑰
  dx : '/:fade', //凋谢
  sa : '/:showlove', //示爱
  xin : '/:heart', //爱心
  xs : '/:break', //心碎
  dg : '/:cake', //蛋糕
  shd : '/:li', //闪电
  zhd : '/:bome', //炸弹
  dao : '/:kn', //刀
  zq : '/:footb', //足球
  pch : '/:ladybug', //瓢虫
  bb : '/:shit', //便便
  yl : '/:moon', //月亮
  ty : '/:sun', //太阳
  lw : '/:gift', //礼物
  yb : '/:hug', //拥抱
  qiang : '/:strong', //强
  ruo : '/:weak', //弱
  ws : '/:share', //握手
  shl : '/:v', //胜利
  bq : '/:@)', //抱拳
  gy : '/:jj', //勾引
  qt : '/:@@', //拳头
  cj : '/:bad', //差劲
  aini : '/:lvu', //爱你
  bu : '/:no', //NO
  hd : '/:ok', //OK
  aiq : '/:love', //爱情
  fw : '/:<L>', //绯闻
  tiao : '/:jump', //跳跳
  fad : '/:shake', //发抖
  oh : '/:<O>', //怄火
  zhq : '/:circle', //转圈
  kt : '/:kotow', //磕头
  ht : '/:turn', //回头
  tsh : '/:skip', //跳绳
  hsh : '/:oY', //挥手
  kaixin : String.fromCharCode(58389), //开心
  kouzhao : String.fromCharCode(58380), //口罩
  daxiao : String.fromCharCode(58386), //笑出泪来
  tushe : String.fromCharCode(58377), //吐舌头
  mengle : String.fromCharCode(58384), //懵了
  jingya : String.fromCharCode(58381), //惊讶
  guichu : String.fromCharCode(57607), //鬼怵
  beishang : String.fromCharCode(58371), //悲伤
  zhayan : String.fromCharCode(58373), //眨眼
  qieyi : String.fromCharCode(58378), //惬意
  qie : String.fromCharCode(58382), //切~
  mogui : String.fromCharCode(57626), //魔鬼
  youling : String.fromCharCode(57627), //幽灵
  aixin : String.fromCharCode(58423), //爱心
  heshi : String.fromCharCode(58397), //双手合十
  jirou : String.fromCharCode(57676), //肌肉
  qiandai : String.fromCharCode(57647), //钱袋
  dangao : String.fromCharCode(58187), //蛋糕
  qingzhu : String.fromCharCode(58130), //庆祝
  liwu : String.fromCharCode(57618) //礼物
}